### ISSUE TITLE
Используйте Environment.NewLine

### ISSUE THREAD

**Issue by lAnubisl** [ArSap88/Millionaire-Game#1]
Не используйте \n потому что на разных платформах перенос строк обозначается по-разному. 
Используйте Environment.NewLine

https://github.com/ArSap88/Millionaire-Game/blob/ae7e9c3e4c908d47a522d8cb9d468a08df96034c/Millionaire%20Game/Program.cs#L13

**Comment by ArSap88** [comment]
Спасибо, не знал про эту команду.
