### ISSUE TITLE
Нет смысла записывать в файл сумму выигрыша

### ISSUE THREAD

**Issue by lAnubisl** [ArSap88/Millionaire-Game#2]
Сумму выигрыша можно вычислить из номера вопроса. Поэтому нет смысла сохранять её в файл.
К тому же странно, зачем вы держите массив для того чтобы из него записывать в файл. Почему вы не можете обратиться к свойствам\полям (имя пользователя из класса User а номер текущего вопроса из класса Game)

https://github.com/ArSap88/Millionaire-Game/blob/ae7e9c3e4c908d47a522d8cb9d468a08df96034c/Millionaire%20Game/Player.cs#L9

**Comment by ArSap88** [comment]
Про выигрыш - не додумался так сделать... Хотя посещала мысль "обезопасить" user.Score от "читеров"))) Добавил цикл в MainGame.GameEngine.
Переработал классы в соответствии с замечанием.
