### ISSUE TITLE
Используйте статические методы

### ISSUE THREAD

**Issue by lAnubisl** [ArSap88/Millionaire-Game#3]
Все методы по заргузке/сохранению игры находятся в классах , в которых нет состояния. (ни полей ни свойств). Поэтому имеет смысл сделать методы статическими и не создавать экземпляры классов чтобы вызвать эти методы.

https://github.com/ArSap88/Millionaire-Game/blob/ae7e9c3e4c908d47a522d8cb9d468a08df96034c/Millionaire%20Game/Load.cs#L18

**Comment by ArSap88** [comment]
Согласен. Сделаю...
