### ISSUE TITLE
Устраните дублирование кода

### ISSUE THREAD

**Issue by lAnubisl** [ArSap88/Millionaire-Game#4]
Вы 4 раза используете один и тот же блок с минимальными выриациями
if (userAnswer == InsideMap.AnswerOne)
if (userAnswer == InsideMap.AnswerTwo)
.....

https://github.com/ArSap88/Millionaire-Game/blob/ae7e9c3e4c908d47a522d8cb9d468a08df96034c/Millionaire%20Game/MainGame.cs#L42

**Comment by ArSap88** [comment]
Мне это дублирование тоже не нравится, но я его сделал из-за вот этих строк:
userChoice = arr[i].Answers[0];        //чтобы проверить correct или нет, надо присвоить значение, ведь так? Можно эти 4 
                    userChoice.Choice();    // блока объединить в 1, но тогда как программа поймет какой правильный ответ??
                    if (userChoice is AnswerCorrect)

**Comment by lAnubisl** [comment]
Я про то, что у вас внутри этих IFов код на 99% одинаковый. Может стоит вынести его в функцию?

**Comment by ArSap88** [comment]
Переработал класс MainGame. Добавил новый метод. Вроде стало красивее... 
Сделал класс Player статичным.
